name: Deploy Labs to Server

on:
  push:
    branches:
      - main # Если у вас ветка называется master, замените на master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            cd /var/www/labs
            git fetch origin ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}